testbed: testbed/testbed_goracle-gard.json
server: aioquic,quic-go,mvfst,quiche,lsquic,picoquic
client: aioquic,quic-go,mvfst,quiche,lsquic,picoquic
test: goodput
repetitions: 50
filesize: 8192
implementation_directory: ./out
use_client_timestamps: True
continue_on_error: True


