testbed: testbed/testbed_amdexp0-amdexp1.json
server: lsquic,lsquic-amdexp0,quiche,quiche-amdexp0,tcp+tls
client: lsquic,lsquic-amdexp0,quiche,quiche-amdexp0,tcp+tls
test: goodput
repetitions: 10
filesize: 8192
implementation_directory: ./out
use_client_timestamps: True
continue_on_error: True
only_same_implementation: True
client_prerunscript:
  - pre-post-scripts/start-pidstat.sh
  - pre-post-scripts/run-ethtool.sh
  - pre-post-scripts/run-netstat.sh
  - pre-post-scripts/set-rcvbuf.sh
  - pre-post-scripts/default-nic-offload.sh
client_postrunscript:
  - pre-post-scripts/stop-pidstat.sh
  - pre-post-scripts/run-ethtool.sh
  - pre-post-scripts/run-netstat.sh
  - pre-post-scripts/set-buffers-default.sh
server_prerunscript:
  - pre-post-scripts/start-pidstat.sh
  - pre-post-scripts/run-ethtool.sh
  - pre-post-scripts/run-netstat.sh
  - pre-post-scripts/set-rcvbuf.sh
  - pre-post-scripts/default-nic-offload.sh
server_postrunscript:
  - pre-post-scripts/stop-pidstat.sh
  - pre-post-scripts/run-ethtool.sh
  - pre-post-scripts/run-netstat.sh
  - pre-post-scripts/set-buffers-default.sh

